# Generated by Django 4.0.1 on 2022-01-29 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('price', models.IntegerField(max_length=256)),
                ('months', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='BUDGTR.month')),
            ],
        ),
    ]
