# Generated by Django 4.0.1 on 2022-01-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BUDGTR', '0002_alter_bill_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='price',
            field=models.CharField(max_length=256),
        ),
    ]
